---
title: "AP_ACMTF"
output: html_document
date: "2025-02-21"
---

```{r libraries}
library(phyloseq)
library(tidyverse)
library(vegan)
library(ape)
library(ggpubr)
library(ggplot2)
library(parafac4microbiome)
library(CMTFtoolbox)
```

```{r load the data}
processedGeorgiou = readRDS("./Data/AP/cytokines_processed.RDS")
microbiome_cnt_scl = readRDS("./Data/AP/microbiome_processed.RDS")
```

```{r prepare input data}
datasets = list(processedGeorgiou$data, as.matrix(microbiome_cnt_scl))
modes = list(c(1,2,3), c(1,4))
Z = setupCMTFdata(datasets, modes, normalize=TRUE)
```

```{r check number of components}
Y = as.numeric(as.factor(processedGeorgiou$mode1$PainS_NopainA))
Ycnt = Y - mean(Y)

result = CMTFtoolbox::ncrossreg(Z, Ycnt, pi=0.95, method="L-BFGS", nstart=5, numCores=parallel::detectCores(), cvFolds=5)
```

```{r run ACMTF}
# model = acmtfr_opt(Z, Ycnt, 1, pi=0.975, method="L-BFGS", nstart=100, numCores=parallel::detectCores())
# saveRDS(model, "./Models/ACMTF/AP_ACMTFR_975.RDS")
model = readRDS("./Models/ACMTF/AP_ACMTFR_975.RDS")
```

```{r plot acmtf model}
a = processedGeorgiou$mode1 %>% mutate(Component_1 = model$Fac[[1]][,1]) %>% arrange(PainS_NopainA,SubjectID) %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=index,y=Component_1,fill=as.factor(PainS_NopainA))) + geom_bar(stat="identity")
```

```{r tests}
otherMeta = read.csv("./Data/AP/Root_meta_data_parafac.txt", sep="\t") %>% as_tibble() %>% select(-Gender)
timepoints = c(-6, -3, 0, 1, 6, 13)

normalSubjectLoadings = processedGeorgiou$mode1 %>% mutate(Component_1 = model$Fac[[1]][,1]) %>% as_tibble() %>% left_join(otherMeta)

uncorrectedP = matrix(NA, nrow=1, ncol=4)

# Gender
uncorrectedP[1,1] = wilcox.test(normalSubjectLoadings %>% filter(Gender=="M") %>% select(Component_1) %>% pull(), normalSubjectLoadings %>% filter(Gender=="F") %>% select(Component_1) %>% pull())$p.value
# uncorrectedP[2,1] = wilcox.test(normalSubjectLoadings %>% filter(Gender=="M") %>% select(Component_2) %>% pull(), normalSubjectLoadings %>% filter(Gender=="F") %>% select(Component_2) %>% pull())$p.value

# Age
uncorrectedP[1,2] = cor.test(normalSubjectLoadings$Component_1, normalSubjectLoadings$Age)$p.value
# uncorrectedP[2,2] = cor.test(normalSubjectLoadings$Component_2, normalSubjectLoadings$Age)$p.value

# DMFT
uncorrectedP[1,3] = cor.test(normalSubjectLoadings$Component_1, normalSubjectLoadings$DMFT)$p.value
# uncorrectedP[2,3] = cor.test(normalSubjectLoadings$Component_2, normalSubjectLoadings$DMFT)$p.value

# pain-noPain
uncorrectedP[1,4] = wilcox.test(normalSubjectLoadings %>% filter(PainS_NopainA=="S") %>% select(Component_1) %>% pull(), normalSubjectLoadings %>% filter(PainS_NopainA=="A") %>% select(Component_1) %>% pull())$p.value
# uncorrectedP[2,4] = wilcox.test(normalSubjectLoadings %>% filter(PainS_NopainA=="S") %>% select(Component_2) %>% pull(), normalSubjectLoadings %>% filter(PainS_NopainA=="A") %>% select(Component_2) %>% pull())$p.value

print(uncorrectedP)
correctedP = matrix(p.adjust(uncorrectedP, "BH"), nrow=1, ncol=4)
print(correctedP)

```
