---
title: "redoPackage"
output: html_document
date: "2024-04-18"
---

```{r libraries}
library(ggplot2)
library(parafac4microbiome)
```

```{r load the data}
processedGeorgiou = readRDS("./Data/AP/cytokines_processed.RDS")
```

```{r Load model}
mode1 = read.csv("./Models/NPLS/AP/AP_mode1.csv", header=FALSE)
colnames(mode1) = c("Component_1", "SubjectID", "PainS_NopainA")
mode2 = read.csv("./Models/NPLS/AP/AP_mode2.csv", header=FALSE)
colnames(mode2) = c("Component_1", "value")
mode3 = read.csv("./Models/NPLS/AP/AP_mode3.csv", header=FALSE)
```

```{r fit sNPLS model as a test}
Y = as.numeric(as.factor(processedGeorgiou$mode1$PainS_NopainA))
Ycnt = Y - mean(Y)

X = processedGeorgiou$data
X[is.na(X)] = 0 # sNPLS cannot handle NAs - very stupid
model = sNPLS::sNPLS(X, as.matrix(Ycnt), 1, threshold_j=0, threshold_k=0, scale.X = FALSE, scale.Y=FALSE, center.X=FALSE, center.Y=FALSE)

newMode1 = cbind(processedGeorgiou$mode1, model$T) %>% as_tibble()
newMode2 = cbind(processedGeorgiou$mode2, model$Wj) %>% as_tibble()

saveRDS(model, "./Models/NPLS/AP_cytokine_NPLS.RDS")
```

```{r plot NPLS model}
prepMode1 = mode1 %>% arrange(PainS_NopainA, SubjectID) %>% mutate(index=1:nrow(.))
prepMode2 = mode2 %>% arrange(value) %>% mutate(index=1:nrow(.))

a = prepMode1 %>% ggplot(aes(x=index,y=Component_1,fill=as.factor(PainS_NopainA))) + geom_bar(stat="identity")
b = prepMode2 %>% ggplot(aes(x=as.factor(value),y=Component_1)) + geom_bar(stat="identity")
c = mode3 %>% as_tibble() %>% mutate(visit = 1:6) %>% ggplot(aes(x=visit,y=V1)) + geom_line() + geom_point()

ggarrange(a,b,c,nrow=1,ncol=3)
```

```{r plot NPLS model from sNPLS}
prepMode1 = newMode1 %>% arrange(PainS_NopainA, SubjectID) %>% mutate(index=1:nrow(.))
prepMode2 = newMode2 %>% arrange(value) %>% mutate(index=1:nrow(.))

a = prepMode1 %>% ggplot(aes(x=index,y=`Comp. 1`,fill=as.factor(PainS_NopainA))) + geom_bar(stat="identity")
b = prepMode2 %>% ggplot(aes(x=as.factor(value),y=`Comp. 1`)) + geom_bar(stat="identity")
c = model$Wk %>% as_tibble() %>% mutate(visit = 1:6) %>% ggplot(aes(x=visit,y=`Comp. 1`)) + geom_line() + geom_point()

ggarrange(a,b,c,nrow=1,ncol=3)
```

```{r tests}
otherMeta = read.csv("./Data/AP/Root_meta_data_parafac.txt", sep="\t") %>% as_tibble() %>% select(-Gender)
timepoints = c(-6, -3, 0, 1, 6, 13)

normalSubjectLoadings = prepMode1 %>% as_tibble() %>% left_join(cytokines_meta_data) %>% left_join(otherMeta,by="SubjectID")

uncorrectedP = matrix(NA, nrow=1, ncol=4)

# Gender
uncorrectedP[1,1] = wilcox.test(normalSubjectLoadings %>% filter(Gender=="M") %>% select(Component_1) %>% pull(), normalSubjectLoadings %>% filter(Gender=="F") %>% select(Component_1) %>% pull())$p.value
# uncorrectedP[2,1] = wilcox.test(normalSubjectLoadings %>% filter(Gender=="M") %>% select(Component_2) %>% pull(), normalSubjectLoadings %>% filter(Gender=="F") %>% select(Component_2) %>% pull())$p.value

# Age
uncorrectedP[1,2] = cor.test(normalSubjectLoadings$Component_1, normalSubjectLoadings$Age.x)$p.value
# uncorrectedP[2,2] = cor.test(normalSubjectLoadings$Component_2, normalSubjectLoadings$Age)$p.value

# DMFT
uncorrectedP[1,3] = cor.test(normalSubjectLoadings$Component_1, normalSubjectLoadings$DMFT)$p.value
# uncorrectedP[2,3] = cor.test(normalSubjectLoadings$Component_2, normalSubjectLoadings$DMFT)$p.value

# pain-noPain
uncorrectedP[1,4] = wilcox.test(normalSubjectLoadings %>% filter(PainS_NopainA.x=="Symptomatic") %>% select(Component_1) %>% pull(), normalSubjectLoadings %>% filter(PainS_NopainA.x=="Asymptomatic") %>% select(Component_1) %>% pull())$p.value
# uncorrectedP[2,4] = wilcox.test(normalSubjectLoadings %>% filter(PainS_NopainA=="S") %>% select(Component_2) %>% pull(), normalSubjectLoadings %>% filter(PainS_NopainA=="A") %>% select(Component_2) %>% pull())$p.value

print(uncorrectedP)
correctedP = matrix(p.adjust(uncorrectedP, "BH"), nrow=1, ncol=4)
print(correctedP)

```
