---
title: "redoPackage"
output: html_document
date: "2024-04-18"
---

```{r libraries}
library(ggplot2)
library(parafac4microbiome)
```

```{r load the data}
cytokines_data = read.csv("./Data/AP/input_deduplicated_RvdP.csv", sep=" ", header=FALSE) %>% as_tibble()
colnames(cytokines_data) = c("VEGF", "CRP", "GM-CSF", "IL1alpha", "IL1beta", "IL4", "IL6", "IL8", "IL10", "IL12p70", "IL17A", "IFNgamma", "MIP1alpha", "OPG", "TNFalpha", "RANKL")

cytokines_meta_data = read.csv("./Data/AP/input_deduplicated_metadata_RvdP.csv", sep=" ", header=FALSE) %>% as_tibble()
colnames(cytokines_meta_data) = c("SubjectID", "Visit", "Gender", "Age", "Pain_noPain", "case_control")

otherMeta = read.csv("./Data/AP/Root_meta_data_parafac.txt", sep="\t") %>% as_tibble() %>% select(-Gender)
```

```{r put into a cube for processing}
I = 52
J = 16
K = 6
cube = array(0L, dim=c(I,J,K))

for(k in 1:K){
  temp = cbind(cytokines_data, cytokines_meta_data) %>% as_tibble()
  cube[,,k] = temp %>%
    filter(Visit == k) %>%
    right_join(cytokines_meta_data %>% select(SubjectID) %>% unique()) %>%
    arrange(SubjectID) %>%
    select(-all_of(colnames(cytokines_meta_data))) %>%
    as.matrix()
}

cube = sqrt(cube)
cube_cnt = multiwayCenter(cube, mode=1)
cube_cnt_scl = multiwayScale(cube_cnt, mode=2)

temp = cytokines_meta_data %>% select(-Visit) %>% unique() %>% arrange(SubjectID)
caseMask = temp$case_control=="case"

processedGeorgiou = list()
processedGeorgiou$mode1 = temp[caseMask,] %>% left_join(otherMeta %>% select(SubjectID, PainS_NopainA) %>% unique())
processedGeorgiou$mode2 = colnames(cytokines_data) %>% as_tibble()
processedGeorgiou$mode3 = cytokines_meta_data %>% select(Visit) %>% arrange(Visit) %>% unique() %>% mutate(extraction = c(rep("Before extraction",3), rep("After extraction",3)))

processedGeorgiou$data = cube_cnt_scl[caseMask,,]
```

```{r PARAFAC of only case}
result = parafac4microbiome::assessModelQuality(processedGeorgiou$data, numRepetitions=10, numCores=parallel::detectCores())
cytokine_parafac = parafac4microbiome::parafac(processedGeorgiou$data, nfac=2, nstart=100)
```

```{r plot PARAFAC model}
prepMode1 = processedGeorgiou$mode1 %>% mutate(Component_1 = cytokine_parafac$Fac[[1]][,1], Component_2 = cytokine_parafac$Fac[[1]][,2]) %>% arrange(PainS_NopainA, SubjectID) %>% mutate(index=1:nrow(.))
prepMode2 = processedGeorgiou$mode2 %>% mutate(Component_1 = cytokine_parafac$Fac[[2]][,1], Component_2 = cytokine_parafac$Fac[[2]][,2]) %>% arrange(value) %>% mutate(index=1:nrow(.))

a = prepMode1 %>% ggplot(aes(x=index,y=Component_1,fill=as.factor(PainS_NopainA))) + geom_bar(stat="identity")
b = prepMode2 %>% ggplot(aes(x=as.factor(value),y=Component_1)) + geom_bar(stat="identity")
c = cytokine_parafac$Fac[[3]] %>% as_tibble() %>% mutate(visit = 1:6) %>% ggplot(aes(x=visit,y=V1)) + geom_line() + geom_point()
d = prepMode1 %>% ggplot(aes(x=index,y=Component_2,fill=as.factor(PainS_NopainA))) + geom_bar(stat="identity")
e = prepMode2 %>% ggplot(aes(x=as.factor(value),y=Component_2)) + geom_bar(stat="identity")
f = cytokine_parafac$Fac[[3]] %>% as_tibble() %>% mutate(visit = 1:6) %>% ggplot(aes(x=visit,y=V2)) + geom_line() + geom_point()

ggarrange(a,b,c,d,e,f,nrow=2,ncol=3)
```

```{r tests}
otherMeta = read.csv("./Data/AP/Root_meta_data_parafac.txt", sep="\t") %>% as_tibble() %>% select(-Gender)
timepoints = c(-6, -3, 0, 1, 6, 13)

normalSubjectLoadings = prepMode1 %>% as_tibble() %>% left_join(otherMeta)

uncorrectedP = matrix(NA, nrow=2, ncol=4)

# Gender
uncorrectedP[1,1] = wilcox.test(normalSubjectLoadings %>% filter(Gender=="M") %>% select(Component_1) %>% pull(), normalSubjectLoadings %>% filter(Gender=="F") %>% select(Component_1) %>% pull())$p.value
uncorrectedP[2,1] = wilcox.test(normalSubjectLoadings %>% filter(Gender=="M") %>% select(Component_2) %>% pull(), normalSubjectLoadings %>% filter(Gender=="F") %>% select(Component_2) %>% pull())$p.value

# Age
uncorrectedP[1,2] = cor.test(normalSubjectLoadings$Component_1, normalSubjectLoadings$Age)$p.value
uncorrectedP[2,2] = cor.test(normalSubjectLoadings$Component_2, normalSubjectLoadings$Age)$p.value

# DMFT
uncorrectedP[1,3] = cor.test(normalSubjectLoadings$Component_1, normalSubjectLoadings$DMFT)$p.value
uncorrectedP[2,3] = cor.test(normalSubjectLoadings$Component_2, normalSubjectLoadings$DMFT)$p.value

# pain-noPain
uncorrectedP[1,4] = wilcox.test(normalSubjectLoadings %>% filter(PainS_NopainA=="S") %>% select(Component_1) %>% pull(), normalSubjectLoadings %>% filter(PainS_NopainA=="A") %>% select(Component_1) %>% pull())$p.value
uncorrectedP[2,4] = wilcox.test(normalSubjectLoadings %>% filter(PainS_NopainA=="S") %>% select(Component_2) %>% pull(), normalSubjectLoadings %>% filter(PainS_NopainA=="A") %>% select(Component_2) %>% pull())$p.value

print(uncorrectedP)
correctedP = matrix(p.adjust(uncorrectedP, "BH"), nrow=2, ncol=4)
print(correctedP)

```
