---
title: "microbiomeAnalysis"
output: html_document
date: "2023-09-05"
---

```{r libraries}
library(phyloseq)
library(tidyverse)
library(vegan)
library(ape)
library(ggpubr)
```

```{r load phyloseq object and convert}
phylo_df = import_biom("./Data/AP/ACTA094_Root/ACTA094_Root/Root_zotu_table_sorted.biom")

df = phylo_df@otu_table %>% as.data.frame() %>% as_tibble() %>% select(all_of(starts_with("S"))) %>% t() %>% as_tibble()
colnames(df) = row.names(phylo_df@otu_table)

sampleMeta = read.csv("./Data/AP/Root_meta_data_parafac.txt", sep="\t") %>% as_tibble()
sampleMeta = sampleMeta %>% select(X.SampleID, SubjectID, Subject, PainS_NopainA)
colnames(sampleMeta) = c("sampleID", "subjectID", "subject", "group")
sampleOrder = colnames(phylo_df@otu_table)[6:34]

taxa = phylo_df@tax_table %>% as.data.frame() %>% as_tibble() %>% mutate(Zotu = row.names(phylo_df@tax_table))
colnames(taxa) = c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species", "Zotu")
```

```{r homogenize}
taxa_reordered = taxa %>% arrange(Zotu)
df_reordered = df %>% mutate(sample = sampleMeta$subjectID) %>% arrange(sample) %>% select(-sample) %>% select(taxa_reordered$Zotu)
sampleMeta_reordered = sampleMeta %>% arrange(subjectID)
```

```{r quick BC}
d = vegdist(df, method="bray")
BC_pcoa = ape::pcoa(d)

BC_plotdata = BC_pcoa$vectors %>% as_tibble() %>% select(Axis.1, Axis.2) %>% mutate(sampleID = sampleOrder) %>% left_join(sampleMeta)
BCplot = BC_plotdata %>% ggplot(aes(x=Axis.1,y=Axis.2,col=as.factor(group))) + geom_point()
BCplot
```

```{r quick Aitchison}
pseudocount = 1
d = vegdist(df+pseudocount, method="aitchison")
A_pcoa = ape::pcoa(d)

A_plotdata = A_pcoa$vectors %>% as_tibble() %>% select(Axis.1, Axis.2) %>% mutate(sampleID = sampleOrder) %>% left_join(sampleMeta)
Aplot = A_plotdata %>% ggplot(aes(x=Axis.1,y=Axis.2,col=as.factor(group))) + geom_point()
Aplot
```
```{r compare with metadata - bc}
cytokines_meta_data = read.csv("./Data/AP/input_deduplicated_metadata_RvdP.csv", sep=" ", header=FALSE) %>% as_tibble()
colnames(cytokines_meta_data) = c("SubjectID", "Visit", "Gender", "Age", "Pain_noPain", "case_control")

otherMeta = read.csv("./Data/AP/Root_meta_data_parafac.txt", sep="\t") %>% as_tibble() %>% select(-Gender)
timepoints = c(-6, -3, 0, 1, 6, 13)

normalSubjectLoadings = BC_plotdata %>% as_tibble() %>% left_join(cytokines_meta_data, by=c("subject"="SubjectID")) %>% left_join(otherMeta, by=c("subject"="SubjectID"))

uncorrectedP = matrix(NA, nrow=2, ncol=4)

# Gender
uncorrectedP[1,1] = wilcox.test(normalSubjectLoadings %>% filter(Gender=="M") %>% select(Axis.1) %>% pull(), normalSubjectLoadings %>% filter(Gender=="F") %>% select(Axis.1) %>% pull())$p.value
uncorrectedP[2,1] = wilcox.test(normalSubjectLoadings %>% filter(Gender=="M") %>% select(Axis.2) %>% pull(), normalSubjectLoadings %>% filter(Gender=="F") %>% select(Axis.2) %>% pull())$p.value

# Age
uncorrectedP[1,2] = cor.test(normalSubjectLoadings$Axis.1, normalSubjectLoadings$Age.x)$p.value
uncorrectedP[2,2] = cor.test(normalSubjectLoadings$Axis.2, normalSubjectLoadings$Age.x)$p.value

# DMFT
uncorrectedP[1,3] = cor.test(normalSubjectLoadings$Axis.1, normalSubjectLoadings$DMFT)$p.value
uncorrectedP[2,3] = cor.test(normalSubjectLoadings$Axis.2, normalSubjectLoadings$DMFT)$p.value

# pain-noPain
uncorrectedP[1,4] = wilcox.test(normalSubjectLoadings %>% filter(PainS_NopainA=="S") %>% select(Axis.1) %>% pull(), normalSubjectLoadings %>% filter(PainS_NopainA=="A") %>% select(Axis.1) %>% pull())$p.value
uncorrectedP[2,4] = wilcox.test(normalSubjectLoadings %>% filter(PainS_NopainA=="S") %>% select(Axis.2) %>% pull(), normalSubjectLoadings %>% filter(PainS_NopainA=="A") %>% select(Axis.2) %>% pull())$p.value

print(uncorrectedP)
correctedP = matrix(p.adjust(uncorrectedP, "BH"), nrow=2, ncol=4)
print(correctedP)
```
```{r compare with metadata - a}
cytokines_meta_data = read.csv("./Data/AP/input_deduplicated_metadata_RvdP.csv", sep=" ", header=FALSE) %>% as_tibble()
colnames(cytokines_meta_data) = c("SubjectID", "Visit", "Gender", "Age", "Pain_noPain", "case_control")

otherMeta = read.csv("./Data/AP/Root_meta_data_parafac.txt", sep="\t") %>% as_tibble() %>% select(-Gender)
timepoints = c(-6, -3, 0, 1, 6, 13)

normalSubjectLoadings = A_plotdata %>% as_tibble() %>% left_join(cytokines_meta_data, by=c("subject"="SubjectID")) %>% left_join(otherMeta, by=c("subject"="SubjectID"))

uncorrectedP = matrix(NA, nrow=2, ncol=4)

# Gender
uncorrectedP[1,1] = wilcox.test(normalSubjectLoadings %>% filter(Gender=="M") %>% select(Axis.1) %>% pull(), normalSubjectLoadings %>% filter(Gender=="F") %>% select(Axis.1) %>% pull())$p.value
uncorrectedP[2,1] = wilcox.test(normalSubjectLoadings %>% filter(Gender=="M") %>% select(Axis.2) %>% pull(), normalSubjectLoadings %>% filter(Gender=="F") %>% select(Axis.2) %>% pull())$p.value

# Age
uncorrectedP[1,2] = cor.test(normalSubjectLoadings$Axis.1, normalSubjectLoadings$Age.x)$p.value
uncorrectedP[2,2] = cor.test(normalSubjectLoadings$Axis.2, normalSubjectLoadings$Age.x)$p.value

# DMFT
uncorrectedP[1,3] = cor.test(normalSubjectLoadings$Axis.1, normalSubjectLoadings$DMFT)$p.value
uncorrectedP[2,3] = cor.test(normalSubjectLoadings$Axis.2, normalSubjectLoadings$DMFT)$p.value

# pain-noPain
uncorrectedP[1,4] = wilcox.test(normalSubjectLoadings %>% filter(PainS_NopainA=="S") %>% select(Axis.1) %>% pull(), normalSubjectLoadings %>% filter(PainS_NopainA=="A") %>% select(Axis.1) %>% pull())$p.value
uncorrectedP[2,4] = wilcox.test(normalSubjectLoadings %>% filter(PainS_NopainA=="S") %>% select(Axis.2) %>% pull(), normalSubjectLoadings %>% filter(PainS_NopainA=="A") %>% select(Axis.2) %>% pull())$p.value

print(uncorrectedP)
correctedP = matrix(p.adjust(uncorrectedP, "BH"), nrow=2, ncol=4)
print(correctedP)
```
