---
title: "BMI_parafac"
output: html_document
date: "2025-02-21"
---

```{r setup}
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(stringr)
library(parafac4microbiome)
library(CMTFtoolbox)
```

```{r processing}
milkMetab_df_bmi = readRDS("./Data/BMI/milkMetab_homogenized.RDS")
milk_df_bmi = readRDS("./Data/BMI/milk_homogenized.RDS")
faeces_df_bmi = readRDS("./Data/BMI/faeces_homogenized.RDS")
homogenized_subjectMeta_bmi = readRDS("./Data/BMI/homogenized_subjectMeta.RDS")
faeces_taxonomy = readRDS("./Data/BMI/faeces_taxonomy.RDS")
milk_taxonomy = readRDS("./Data/BMI/milk_taxonomy.RDS")
milkMetab_featureMeta = readRDS("./Data/BMI/milk_metabolites.RDS")
```

```{r prepare input data}
datasets = list(faeces_df_bmi, milk_df_bmi, milkMetab_df_bmi)
modes = list(c(1,2,3), c(1,4,5), c(1,6,7))
Z = setupCMTFdata(datasets, modes, normalize=TRUE)
```

```{r check number of components}
result = investigateFMS(datasets, modes, sharedMode=1, maxNumComponents=5, numFolds=10, numCores = parallel::detectCores(), method="L-BFGS")
```

```{r fit model}
model = CMTFtoolbox::acmtf_opt(Z, 2)
```

```{r interpret loadings}
testAssociationsPerComponent = function(model){
  numComponents = ncol(model$Fac[[1]])
  
  result = matrix(NA, nrow=numComponents, ncol=5)
  
  for(i in 1:numComponents){
    result[i,1] = cor.test(model$Fac[[1]][,i], Jakobsen2025$subjectMeta_BMI$BMI, method="spearman")$p.value
    result[i,2] = cor.test(model$Fac[[1]][,i], Jakobsen2025$subjectMeta_BMI$whz.6m, method="spearman")$p.value
    
    mask = !is.na(Jakobsen2025$subjectMeta_BMI$C.section)
    temp = model$Fac[[1]][mask,i]
    tempMeta = Jakobsen2025$subjectMeta_BMI[mask,]
    mask1 = tempMeta$C.section == 1
    mask2 = tempMeta$C.section == 2
    
    result[i,3] = wilcox.test(temp[mask1], temp[mask2])$p.value
    
    mask1 = Jakobsen2025$subjectMeta_BMI$Secretor == 0
    mask2 = Jakobsen2025$subjectMeta_BMI$Secretor == 1
    result[i,4] = wilcox.test(model$Fac[[1]][mask1,i], model$Fac[[1]][mask2,i])$p.value
    
    mask1 = Jakobsen2025$subjectMeta_BMI$Lewis == 0
    mask2 = Jakobsen2025$subjectMeta_BMI$Lewis == 1
    result[i,5] = wilcox.test(model$Fac[[1]][mask1,i], model$Fac[[1]][mask2,i])$p.value
  }
  
  return(result)
}

result1 = testAssociationsPerComponent(model)

df = rbind(result1)
corrected_df = signif(matrix(p.adjust(df, "BH"), dim(df)), 2)
```

```{r check varExps}
Xhat_faeces = reinflateTensor(faeces_NPLS$T, faeces_NPLS$Wj, faeces_NPLS$Wk)
X_faeces = faeces_df_bmi
X_faeces[is.na(X_faeces)] = 0
sum(Xhat_faeces^2) / sum(X_faeces^2)

Xhat_milk = reinflateTensor(milk_NPLS$T, milk_NPLS$Wj, milk_NPLS$Wk)
X_milk = milk_df_bmi
X_milk[is.na(X_milk)] = 0
sum(Xhat_milk^2) / sum(X_milk^2)

Xhat_milkMetab = reinflateTensor(milkMetab_NPLS$T, milkMetab_NPLS$Wj, milkMetab_NPLS$Wk)
X_milkMetab = milkMetab_df_bmi
X_milkMetab[is.na(X_milkMetab)] = 0
sum(Xhat_milkMetab^2) / sum(X_milkMetab^2)
```
