---
title: "BMI_parafac"
output: html_document
date: "2025-02-21"
---

```{r setup}
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(stringr)
library(parafac4microbiome)
library
```

```{r processing}
milkMetab = readRDS("./Data/BMI/milkMetab.RDS")
milk = readRDS("./Data/BMI/milk.RDS")
faeces = readRDS("./Data/BMI/faeces.RDS")
```

```{r parafac of infant faecal microbiome}
# result = parafac4microbiome::assessModelQuality(faeces$data, numRepetitions=10, numCores=parallel::detectCores())
# result$plots$overview
# result2 = parafac4microbiome::assessModelStability(faeces, maxNumComponents=3, numFolds=10)
# modelFaeces = parafac4microbiome::parafac(faeces$data, nfac=2, nstart=100)
# saveRDS(modelFaeces, "./Models/PARAFAC/BMI_faeces.RDS")
modelFaeces = readRDS("./Models/PARAFAC/BMI_faeces.RDS")
```

```{r parafac of HM microbiome}
# result = parafac4microbiome::assessModelQuality(milk$data, numRepetitions=10, numCores=parallel::detectCores())
# result$plots$overview
# result2 = parafac4microbiome::assessModelStability(milk, maxNumComponents=3, numFolds=10)
# modelMilk = parafac4microbiome::parafac(milk$data, nfac=3, nstart=100)
# saveRDS(modelMilk, "./Models/PARAFAC/BMI_milk.RDS")
modelMilk = readRDS("./Models/PARAFAC/BMI_milk.RDS")
```

```{r parafac of HM metabolomics}
# result = parafac4microbiome::assessModelQuality(milkMetab$data, numRepetitions=10, numCores=parallel::detectCores())
# result$plots$overview
# result2 = parafac4microbiome::assessModelStability(milkMetab, maxNumComponents=3, numFolds=10)
# modelMilkMetab = parafac4microbiome::parafac(milkMetab$data, nfac=3, nstart=100)
# saveRDS(modelMilkMetab, "./Models/PARAFAC/BMI_milkMetab.RDS")
modelMilkMetab = readRDS("./Models/PARAFAC/BMI_milkMetab.RDS")
```

```{r plot HM metabolomics model}
prepMode1 = homogenized_subjectMeta_bmi %>% mutate(Component_1 = milkMetab_parafac$Fac[[1]]) %>% arrange(Secretor,subject) %>% mutate(index=1:nrow(.))
prepMode2 = milkMetab_featureMeta %>% mutate(Component_1 = milkMetab_parafac$Fac[[2]]) %>% arrange(Class, Metabolite) %>% mutate(index=1:nrow(.))

a = prepMode1 %>% ggplot(aes(x=index,y=Component_1,fill=as.factor(Secretor))) + geom_bar(stat="identity")
b = prepMode2 %>% ggplot(aes(x=index,y=Component_1,fill=as.factor(Class))) + geom_bar(stat="identity")
c = milkMetab_parafac$Fac[[3]] %>% as_tibble() %>% mutate(timepoint = c(3,30,60,90)) %>% ggplot(aes(x=timepoint,y=V1)) + geom_line() + geom_point()

ggarrange(a,b,c,nrow=1,ncol=3)
```

```{r plot HM microbiome model}
prepMode1 = homogenized_subjectMeta_bmi %>% mutate(Component_1 = milk_parafac$Fac[[1]]) %>% arrange(BMI.group,subject) %>% mutate(index=1:nrow(.))
prepMode2 = milk_taxonomy %>% mutate(Component_1 = milk_parafac$Fac[[2]]) %>% arrange(V3, V1) %>% mutate(index=1:nrow(.))

a = prepMode1 %>% ggplot(aes(x=index,y=Component_1,fill=as.factor(BMI.group))) + geom_bar(stat="identity")
b = prepMode2 %>% ggplot(aes(x=index,y=Component_1,fill=as.factor(V3))) + geom_bar(stat="identity")
c = milk_parafac$Fac[[3]] %>% as_tibble() %>% mutate(timepoint = c(3,30,60,90)) %>% ggplot(aes(x=timepoint,y=V1)) + geom_line() + geom_point()

ggarrange(a,b,c,nrow=1,ncol=3)
```
```{r plot faecal microbiome model}
prepMode1 = homogenized_subjectMeta_bmi %>% mutate(Component_1 = faeces_parafac$Fac[[1]]) %>% arrange(BMI.group,subject) %>% mutate(index=1:nrow(.))
prepMode2 = faeces_taxonomy %>% mutate(Component_1 = faeces_parafac$Fac[[2]]) %>% arrange(V3, V1) %>% mutate(index=1:nrow(.))

a = prepMode1 %>% ggplot(aes(x=index,y=Component_1,fill=as.factor(BMI.group))) + geom_bar(stat="identity")
b = prepMode2 %>% ggplot(aes(x=index,y=Component_1,fill=as.factor(V3))) + geom_bar(stat="identity")
c = faeces_parafac$Fac[[3]] %>% as_tibble() %>% mutate(timepoint = c(30,60,90)) %>% ggplot(aes(x=timepoint,y=V1)) + geom_line() + geom_point()

ggarrange(a,b,c,nrow=1,ncol=3)
```

```{r interpret loadings}
testAssociationsPerComponent = function(model, metadata){
  numComponents = ncol(model$Fac[[1]])
  
  result = matrix(NA, nrow=numComponents, ncol=5)
  
  for(i in 1:numComponents){
    result[i,1] = cor.test(model$Fac[[1]][,i], metadata$BMI, method="spearman")$p.value
    result[i,2] = cor.test(model$Fac[[1]][,i], metadata$whz.6m, method="spearman")$p.value
    
    mask = !is.na(metadata$C.section)
    temp = model$Fac[[1]][mask,i]
    tempMeta = metadata[mask,]
    mask1 = tempMeta$C.section == 1
    mask2 = tempMeta$C.section == 2
    
    result[i,3] = wilcox.test(temp[mask1], temp[mask2])$p.value
    
    mask1 = metadata$Secretor == 0
    mask2 = metadata$Secretor == 1
    result[i,4] = wilcox.test(model$Fac[[1]][mask1,i], model$Fac[[1]][mask2,i])$p.value
    
    mask1 = metadata$Lewis == 0
    mask2 = metadata$Lewis == 1
    result[i,5] = wilcox.test(model$Fac[[1]][mask1,i], model$Fac[[1]][mask2,i])$p.value
  }
  
  return(result)
}

result1 = testAssociationsPerComponent(modelFaeces, faeces$mode1 %>% left_join(Jakobsen2025$subjectMeta_BMI))
result2 = testAssociationsPerComponent(modelMilk, milk$mode1 %>% left_join(Jakobsen2025$subjectMeta_BMI))
result3 = testAssociationsPerComponent(modelMilkMetab, milkMetab$mode1 %>% left_join(Jakobsen2025$subjectMeta_BMI))

df = rbind(result1, result2, result3)
corrected_df = signif(matrix(p.adjust(df, "BH"), dim(df)), 2)
```
