---
title: "pfac_pkg"
output: html_document
date: "2024-03-21"
---

```{r library}
library(tidyverse)
library(vegan)
library(ggpubr)
library(ape)
library(Polychrome)
library(parafac4microbiome)
library(CMTFtoolbox)
```

```{r load datasets}
processedTongue = readRDS("./Data/GOHTRANS/tongue_homogenized.RDS")
processedSaliva = readRDS("./Data/GOHTRANS/saliva_homogenized.RDS")
processedCytokine = readRDS("./Data/GOHTRANS/cytokine_homogenized.RDS")

sampleMeta = read.csv("./Data/GOHTRANS/sampleInfo_fixed.csv", sep=" ") %>% as_tibble()
tongueSampleMeta = sampleMeta[sampleMeta$Niche == "Tongue",]
salivaSampleMeta = sampleMeta[sampleMeta$Niche == "Saliva",]

# Load other metadata and ph
ph_BOMP = read_delim("Data/GOHTRANS/GOH-TRANS_csv_export_20240205114955/GOH-TRANS_export_20240205.csv",
                     delim = ";", escape_double = FALSE, trim_ws = TRUE) %>% as_tibble()

df1 = ph_BOMP %>% select(`Participant Id`, starts_with("5.")) %>% mutate(subject = 1:42, numTeeth = `5.1|Number of teeth`, DMFT = `5.2|DMFT`, numBleedingSites = `5.3|Bleeding sites`, boppercent = `5.4|BOP%`, DPSI = `5.5|DPSI`, pH = `5.8|pH`) %>% select(subject, numTeeth, DMFT, numBleedingSites, boppercent, DPSI, pH)
df2 = ph_BOMP %>% select(`Participant Id`, starts_with("12.")) %>% mutate(subject = 1:42, numTeeth = `12.1|Number of teeth`, DMFT = `12.2|DMFT`, numBleedingSites = `12.3|Bleeding sites`, boppercent = `12.4|BOP%`, DPSI = `12.5|DPSI`, pH = `12.8|pH`) %>% select(subject, numTeeth, DMFT, numBleedingSites, boppercent, DPSI, pH)
df3 = ph_BOMP %>% select(`Participant Id`, starts_with("19.")) %>% mutate(subject = 1:42, numTeeth = `19.1|Number of teeth`, DMFT = `19.2|DMFT`, numBleedingSites = `19.3|Bleeding sites`, boppercent = `19.4|BOP%`, DPSI = `19.5|DPSI`, pH = `19.8|pH`) %>% select(subject, numTeeth, DMFT, numBleedingSites, boppercent, DPSI, pH)
df4 = ph_BOMP %>% select(`Participant Id`, starts_with("26.")) %>% mutate(subject = 1:42, numTeeth = `26.1|Number of teeth`, DMFT = `26.2|DMFT`, numBleedingSites = `26.3|Bleeding sites`, boppercent = `26.4|BOP%`, DPSI = `26.5|DPSI`, pH = `26.8|pH`) %>% select(subject, numTeeth, DMFT, numBleedingSites, boppercent, DPSI, pH)

otherMeta = rbind(df1, df2, df3, df4) %>% as_tibble() %>% mutate(newTimepoint = rep(c(0,3,6,12), each=42))

# Remove pH measurements of lower than 0
otherMeta = otherMeta[!otherMeta$pH < 1,] %>% as_tibble()
```

```{r prepare input data}
datasets = list(processedTongue$data, processedSaliva$data, processedCytokine$data)
modes = list(c(1,2,3), c(1,4,5), c(1,6,7))
Z = setupCMTFdata(datasets, modes, normalize=TRUE)
```

```{r check number of components}
result = investigateFMS(datasets, modes, sharedMode=1, maxNumComponents=3, numFolds=5, numCores = parallel::detectCores(), method="L-BFGS")
```

```{r fit model}
model = CMTFtoolbox::acmtf_opt(Z, 1)
```

```{r test metadata - tongue}
timepoints = c(0, 3, 6, 12)

# Tongue
normalSubjectLoadings = processedTongue$mode1 %>% as_tibble() %>% mutate(Component_1 = model$Fac[[1]][,1])
transformedSubjectLoadings = transformPARAFACloadings(model$Fac[c(1,2,3)], 2, moreOutput=TRUE)$Ftilde %>% as_tibble() %>% mutate(subject = rep(processedTongue$mode1$subject, each=4), newTimepoint = rep(timepoints, 27))

uncorrectedP = rep(NA, 14)

# GenderID
uncorrectedP[1] = wilcox.test(normalSubjectLoadings %>% filter(GenderID=="TM") %>% select(Component_1) %>% pull(), normalSubjectLoadings %>% filter(GenderID=="TW") %>% select(Component_1) %>% pull())$p.value

# Age
temp = normalSubjectLoadings %>% left_join(tongueSampleMeta %>% select(subject, GenderID, Age))
uncorrectedP[2] = cor.test(temp$Component_1, temp$Age)$p.value

# Estradiol
temp = transformedSubjectLoadings %>% left_join(tongueSampleMeta) %>% select(V1, newTimepoint, Estradiol_pmol_ml)
uncorrectedP[3] = cor.test(temp$V1, temp$Estradiol_pmol_ml)$p.value

# Testosterone
temp = transformedSubjectLoadings %>% left_join(tongueSampleMeta) %>% select(V1, newTimepoint, Testosterone_nmol_L)
uncorrectedP[4] = cor.test(temp$V1, temp$Testosterone_nmol_L)$p.value

# LH
temp = transformedSubjectLoadings %>% left_join(tongueSampleMeta) %>% select(V1, newTimepoint, LH_U_L)
uncorrectedP[5] = cor.test(temp$V1, temp$LH_U_L)$p.value

# SHBG
temp = transformedSubjectLoadings %>% left_join(tongueSampleMeta) %>% select(V1, newTimepoint, SHBG_nmol_L)
uncorrectedP[6] = cor.test(temp$V1, temp$SHBG_nmol_L)$p.value

# MUC5B
temp = transformedSubjectLoadings %>% left_join(tongueSampleMeta) %>% select(V1, newTimepoint, MUC_5_B_ug_ml)
uncorrectedP[7] = cor.test(temp$V1, temp$MUC_5_B_ug_ml)$p.value

# Chitinase
temp = transformedSubjectLoadings %>% left_join(tongueSampleMeta) %>% select(V1, newTimepoint, Chitinase_AU_ml)
uncorrectedP[8] = cor.test(temp$V1, temp$Chitinase_AU_ml)$p.value

# S-igA
temp = transformedSubjectLoadings %>% left_join(tongueSampleMeta) %>% select(V1, newTimepoint, S_IgA_ug_ml)
uncorrectedP[9] = cor.test(temp$V1, temp$S_IgA_ug_ml)$p.value

# Lysozyme
temp = transformedSubjectLoadings %>% left_join(tongueSampleMeta) %>% select(V1, newTimepoint, Lysozyme_U_ml)
uncorrectedP[10] = cor.test(temp$V1, temp$Lysozyme_U_ml)$p.value

# Amylase
temp = transformedSubjectLoadings %>% left_join(tongueSampleMeta) %>% select(V1, newTimepoint, Amylase_U_ml)
uncorrectedP[11] = cor.test(temp$V1, temp$Amylase_U_ml)$p.value

# Total protein
temp = transformedSubjectLoadings %>% left_join(tongueSampleMeta) %>% select(V1, newTimepoint, Total_protein_ug_ml)
uncorrectedP[12] = cor.test(temp$V1, temp$Total_protein_ug_ml)$p.value

# BOMP
temp = transformedSubjectLoadings %>% left_join(otherMeta) %>% select(V1, newTimepoint, boppercent)
uncorrectedP[13] = cor.test(temp$V1, temp$boppercent)$p.value

# pH
temp = transformedSubjectLoadings %>% left_join(otherMeta) %>% select(V1, newTimepoint, pH)
uncorrectedP[14] = cor.test(temp$V1, temp$pH)$p.value

print(uncorrectedP)
correctedP = p.adjust(uncorrectedP, "BH")
print(correctedP)
```
