---
title: "Comparison"
output: html_document
date: "2025-07-01"
---

```{r setup}
library(tidyverse)
library(forcats)
library(ggplot2)
library(ggpubr)
library(stringr)
library(parafac4microbiome)
library(NPLStoolbox)
library(CMTFtoolbox)
library(vegan)
library(scales)
library(ggrepel)
```

# Useful functions

```{r functions}
calculateTCC = function(vect1, vect2){
  
  vect1 = as.matrix(vect1)
  vect2 = as.matrix(vect2)
  FMS = abs(t(vect1) %*% vect2) / (norm(vect1, "F") * norm(vect2, "F"))
  return(FMS)
}
```

# Extra data
```{r import metadata}
ph_BOMP = read_delim("../GOHTRANS/GOH-TRANS_export_20240205.csv",
                     delim = ";", escape_double = FALSE, trim_ws = TRUE) %>% as_tibble()

df1 = ph_BOMP %>% select(`Participant Id`, starts_with("5.")) %>% mutate(subject = 1:42, numTeeth = `5.1|Number of teeth`, DMFT = `5.2|DMFT`, numBleedingSites = `5.3|Bleeding sites`, boppercent = `5.4|BOP%`, DPSI = `5.5|DPSI`, pH = `5.8|pH`) %>% select(subject, numTeeth, DMFT, numBleedingSites, boppercent, DPSI, pH)
df2 = ph_BOMP %>% select(`Participant Id`, starts_with("12.")) %>% mutate(subject = 1:42, numTeeth = `12.1|Number of teeth`, DMFT = `12.2|DMFT`, numBleedingSites = `12.3|Bleeding sites`, boppercent = `12.4|BOP%`, DPSI = `12.5|DPSI`, pH = `12.8|pH`) %>% select(subject, numTeeth, DMFT, numBleedingSites, boppercent, DPSI, pH)
df3 = ph_BOMP %>% select(`Participant Id`, starts_with("19.")) %>% mutate(subject = 1:42, numTeeth = `19.1|Number of teeth`, DMFT = `19.2|DMFT`, numBleedingSites = `19.3|Bleeding sites`, boppercent = `19.4|BOP%`, DPSI = `19.5|DPSI`, pH = `19.8|pH`) %>% select(subject, numTeeth, DMFT, numBleedingSites, boppercent, DPSI, pH)
df4 = ph_BOMP %>% select(`Participant Id`, starts_with("26.")) %>% mutate(subject = 1:42, numTeeth = `26.1|Number of teeth`, DMFT = `26.2|DMFT`, numBleedingSites = `26.3|Bleeding sites`, boppercent = `26.4|BOP%`, DPSI = `26.5|DPSI`, pH = `26.8|pH`) %>% select(subject, numTeeth, DMFT, numBleedingSites, boppercent, DPSI, pH)

otherMeta = rbind(df1, df2, df3, df4) %>% as_tibble() %>% mutate(newTimepoint = rep(c(0,3,6,12), each=42))
otherMeta = otherMeta %>% select(subject, newTimepoint, boppercent)
otherMeta[otherMeta$boppercent < 0 & !is.na(otherMeta$boppercent), "boppercent"] = NA

saliva_sampleMeta = read.csv("../GOHTRANS/sampleInfo_fixed.csv", sep=" ") %>% as_tibble() %>% select(subject, GenderID, Age, newTimepoint)

# CODS XI
df = read.csv("../GOHTRANS/CODS_XI.csv")
df = df[1:40,1:10] %>% as_tibble() %>% filter(Participant_code %in% saliva_sampleMeta$subject)

CODS = df %>% select(Participant_code, CODS_BASELINE, CODS_3_MONTHS, CODS_6_MONTHS, CODS_12_MONTHS) %>% pivot_longer(-Participant_code) %>% mutate(timepoint = NA)
CODS[CODS$name == "CODS_BASELINE", "timepoint"] = 0
CODS[CODS$name == "CODS_3_MONTHS", "timepoint"] = 3
CODS[CODS$name == "CODS_6_MONTHS", "timepoint"] = 6
CODS[CODS$name == "CODS_12_MONTHS", "timepoint"] = 12
CODS[CODS$value == -99, "value"] = NA
CODS = CODS %>% mutate(subject = Participant_code, newTimepoint = timepoint, CODS = value) %>% select(-Participant_code, -name, -value, -timepoint)

XI = df %>% select(Participant_code, XI_BASELINE, XI_3_MONTHS, XI_6_MONTHS, XI_12_MONTHS) %>% pivot_longer(-Participant_code) %>% mutate(timepoint = NA)
XI[XI$name == "XI_BASELINE", "timepoint"] = 0
XI[XI$name == "XI_3_MONTHS", "timepoint"] = 3
XI[XI$name == "XI_6_MONTHS", "timepoint"] = 6
XI[XI$name == "XI_12_MONTHS", "timepoint"] = 12
XI[XI$value == -99, "value"] = NA
XI = XI %>% mutate(subject = Participant_code, newTimepoint = timepoint, XI = value) %>% select(-Participant_code, -name, -value, -timepoint)

df = otherMeta %>% left_join(CODS) %>% left_join(XI) %>% select(subject, newTimepoint, boppercent, CODS, XI) %>% filter(newTimepoint != "NA")

meta = df %>% left_join(otherMeta) %>% left_join(saliva_sampleMeta) %>% unique()
meta[meta < 0] <- NA
meta$GenderID = as.numeric(as.factor(meta$GenderID)) - 1

staticMeta = meta %>% filter(newTimepoint == 0) %>% select(subject, GenderID, Age)
dynamicMeta = meta %>% select(-GenderID, -Age)
# 
# newBOP = residuals(lm(boppercent ~ GenderID + Age + CODS + XI, data=meta, na.action=na.exclude))
# newCODS= residuals(lm(CODS ~ boppercent + GenderID + Age + XI, data=meta, na.action=na.exclude))
# newXI = residuals(lm(XI ~ boppercent + GenderID + Age + CODS, data=meta, na.action=na.exclude))
# 
# meta = meta %>% mutate(boppercent = newBOP, CODS = newCODS, XI = newXI)
```

# Processing

```{r cp processing}
processedTongue_cp = processDataCube(NPLStoolbox::Cornejo2025$Tongue_microbiome, sparsityThreshold = 0.5, considerGroups=TRUE, groupVariable="GenderID", CLR=TRUE, centerMode=1, scaleMode=2)
processedSaliva_cp = processDataCube(NPLStoolbox::Cornejo2025$Salivary_microbiome, sparsityThreshold = 0.5, considerGroups=TRUE, groupVariable="GenderID", CLR=TRUE, centerMode=1, scaleMode=2)

processedCytokines_cp = NPLStoolbox::Cornejo2025$Salivary_cytokines
processedCytokines_cp$data = log(processedCytokines_cp$data + 0.1300)
# Remove subject 1, 18, 19, and 27 due to being an outlier
processedCytokines_cp$data = processedCytokines_cp$data[-c(1,9,10,19),,]
processedCytokines_cp$mode1 = processedCytokines_cp$mode1[-c(1,9,10,19),]
processedCytokines_cp$data = multiwayCenter(processedCytokines_cp$data, 1)
processedCytokines_cp$data = multiwayScale(processedCytokines_cp$data, 2)

processedBiochemistry_cp = NPLStoolbox::Cornejo2025$Salivary_biochemistry
processedBiochemistry_cp$data = log(processedBiochemistry_cp$data)
processedBiochemistry_cp$data = multiwayCenter(processedBiochemistry_cp$data, 1)
processedBiochemistry_cp$data = multiwayScale(processedBiochemistry_cp$data, 2)

processedHormones_cp = NPLStoolbox::Cornejo2025$Circulatory_hormones
processedHormones_cp$data = log(processedHormones_cp$data)
processedHormones_cp$data = multiwayCenter(processedHormones_cp$data, 1)
processedHormones_cp$data = multiwayScale(processedHormones_cp$data, 2)
```

```{r npls processing}
deltaT = NPLStoolbox::Cornejo2025$Circulatory_hormones$data[,1,2] - NPLStoolbox::Cornejo2025$Circulatory_hormones$data[,1,1]
outcome = processedHormones_cp$mode1 %>% mutate(deltaT = deltaT) %>% filter(deltaT != "NA")

processedTongue_npls = processDataCube(NPLStoolbox::Cornejo2025$Tongue_microbiome, sparsityThreshold = 0.5, considerGroups=TRUE, groupVariable="GenderID", CLR=TRUE, centerMode=FALSE, scaleMode=FALSE)
mask = processedTongue_npls$mode1$subject %in% outcome$subject
processedTongue_npls$mode1 = processedTongue_npls$mode1[mask,]
processedTongue_npls$data = processedTongue_npls$data[mask,,]
processedTongue_npls$data = multiwayCenter(processedTongue_npls$data, 1)
processedTongue_npls$data = multiwayScale(processedTongue_npls$data, 2)

processedSaliva_npls = processDataCube(NPLStoolbox::Cornejo2025$Salivary_microbiome, sparsityThreshold = 0.5, considerGroups=TRUE, groupVariable="GenderID", CLR=TRUE, centerMode=1, scaleMode=2)
mask = processedSaliva_npls$mode1$subject %in% outcome$subject
processedSaliva_npls$mode1 = processedSaliva_npls$mode1[mask,]
processedSaliva_npls$data = processedSaliva_npls$data[mask,,]
processedSaliva_npls$data = multiwayCenter(processedSaliva_npls$data, 1)
processedSaliva_npls$data = multiwayScale(processedSaliva_npls$data, 2)

processedCytokines_npls = NPLStoolbox::Cornejo2025$Salivary_cytokines
processedCytokines_npls$data = log(processedCytokines_npls$data + 0.1300)
# Remove subject 1, 18, 19, and 27 due to being an outlier
processedCytokines_npls$data = processedCytokines_npls$data[-c(1,9,10,19),,]
processedCytokines_npls$mode1 = processedCytokines_npls$mode1[-c(1,9,10,19),]
mask = processedCytokines_npls$mode1$subject %in% outcome$subject
processedCytokines_npls$mode1 = processedCytokines_npls$mode1[mask,]
processedCytokines_npls$data = processedCytokines_npls$data[mask,,]
processedCytokines_npls$data = multiwayCenter(processedCytokines_npls$data, 1)
processedCytokines_npls$data = multiwayScale(processedCytokines_npls$data, 2)

processedBiochemistry_npls = NPLStoolbox::Cornejo2025$Salivary_biochemistry
processedBiochemistry_npls$data = log(processedBiochemistry_npls$data)
mask = processedBiochemistry_npls$mode1$subject %in% outcome$subject
processedBiochemistry_npls$mode1 = processedBiochemistry_npls$mode1[mask,]
processedBiochemistry_npls$data = processedBiochemistry_npls$data[mask,,]
processedBiochemistry_npls$data = multiwayCenter(processedBiochemistry_npls$data, 1)
processedBiochemistry_npls$data = multiwayScale(processedBiochemistry_npls$data, 2)
```

```{r acmtf processing}
deltaT = NPLStoolbox::Cornejo2025$Circulatory_hormones$data[,1,2] - NPLStoolbox::Cornejo2025$Circulatory_hormones$data[,1,1]
outcome = NPLStoolbox::Cornejo2025$Circulatory_hormones$mode1 %>% mutate(deltaT = deltaT) %>% filter(deltaT != "NA")

homogenizedSamples1 = intersect(NPLStoolbox::Cornejo2025$Tongue_microbiome$mode1$subject, outcome$subject)
homogenizedSamples2 = intersect(NPLStoolbox::Cornejo2025$Salivary_microbiome$mode1$subject, outcome$subject)
homogenizedSamples3 = intersect(NPLStoolbox::Cornejo2025$Salivary_cytokines$mode1$subject, outcome$subject)
homogenizedSamples4 = intersect(NPLStoolbox::Cornejo2025$Salivary_biochemistry$mode1$subject, outcome$subject)

homogenizedSamples = intersect(intersect(homogenizedSamples1, homogenizedSamples2), intersect(homogenizedSamples3,homogenizedSamples4))

outcome = outcome %>% filter(subject %in% homogenizedSamples)

# Tongue
newTongue = NPLStoolbox::Cornejo2025$Tongue

mask = newTongue$mode1$subject %in% homogenizedSamples
newTongue$data = newTongue$data[mask,,]
newTongue$mode1 = newTongue$mode1[mask,]

processedTongue_acmtf = processDataCube(newTongue, sparsityThreshold = 0.5, considerGroups=TRUE, groupVariable="GenderID", CLR=TRUE, centerMode=1, scaleMode=2)

# Saliva
newSaliva = NPLStoolbox::Cornejo2025$Salivary_microbiome

mask = newSaliva$mode1$subject %in% homogenizedSamples
newSaliva$data = newSaliva$data[mask,,]
newSaliva$mode1 = newSaliva$mode1[mask,]

processedSaliva_acmtf = processDataCube(newSaliva, sparsityThreshold = 0.5, considerGroups=TRUE, groupVariable="GenderID", CLR=TRUE, centerMode=1, scaleMode=2)

# Cytokines
newCytokines = NPLStoolbox::Cornejo2025$Salivary_cytokines

mask = newCytokines$mode1$subject %in% homogenizedSamples
newCytokines$data = log(newCytokines$data[mask,,] + 0.1300)
newCytokines$mode1 = newCytokines$mode1[mask,]

processedCytokines_acmtf = processDataCube(newCytokines, CLR=FALSE, centerMode=1, scaleMode=2)

# Biochemistry
newBio = NPLStoolbox::Cornejo2025$Salivary_biochemistry

mask = newBio$mode1$subject %in% homogenizedSamples
newBio$data = log(newBio$data[mask,,])
newBio$mode1 = newBio$mode1[mask,]

processedBiochemistry_acmtf = processDataCube(newBio, CLR=FALSE, centerMode=1, scaleMode=2)
```

## Import models

```{r load models}
cp_tongue = readRDS("../GOHTRANS/cp_tongue.RDS")
cp_saliva = readRDS("../GOHTRANS/cp_saliva.RDS")
cp_cytokines = readRDS("../GOHTRANS/cp_cytokines.RDS")
cp_biochemistry = readRDS("../GOHTRANS/cp_biochemistry.RDS")
cp_hormones = readRDS("../GOHTRANS/cp_hormones.RDS")

npls_tongue = readRDS("../GOHTRANS/NPLS_tongue_deltaT.RDS")
npls_saliva = readRDS("../GOHTRANS/NPLS_saliva_deltaT.RDS")
npls_cyto = readRDS("../GOHTRANS/NPLS_cyto_deltaT.RDS")
npls_bio = readRDS("../GOHTRANS/NPLS_bio_deltaT.RDS")

acmtf_model = readRDS("../GOHTRANS/20250815_4block/GOHTRANS_ACMTFR_model_1_deltaT.RDS")
acmtfr_model = readRDS("../GOHTRANS/20250815_4block/GOHTRANS_ACMTFR_model_90_deltaT.RDS")
```

## Test against metadata

```{r metadata test table for mode A}
clinical_metadata = NPLStoolbox::Cornejo2025$Clinical_measurements$mode1 %>% mutate(BOP = NPLStoolbox::Cornejo2025$Clinical_measurements$data[,1,2], CODS = NPLStoolbox::Cornejo2025$Clinical_measurements$data[,2,2], XI = NPLStoolbox::Cornejo2025$Clinical_measurements$data[,3,2]) %>% left_join(NPLStoolbox::Cornejo2025$Subject_metadata %>% mutate(subject = as.character(subject)))

testMetadata = function(model, comp, metadata){
  transformedSubjectLoadings = model$Fac[[1]][,comp]
  transformedSubjectLoadings = transformedSubjectLoadings / norm(transformedSubjectLoadings, "2")
  
  metadata = metadata$mode1 %>% left_join(clinical_metadata) %>% mutate(GenderID = as.numeric(as.factor(GenderID))-1)
  
  result = lm(transformedSubjectLoadings ~ GenderID + Age + BOP + CODS + XI, data=metadata)
  
  # Extract coefficients and confidence intervals
  coef_estimates <- summary(result)$coefficients
  conf_intervals <- confint(result)
  
  # Remove intercept
  coef_estimates <- coef_estimates[rownames(coef_estimates) != "(Intercept)", ]
  conf_intervals <- conf_intervals[rownames(conf_intervals) != "(Intercept)", ]
  
  # Combine into a clean data frame
  summary_table <- data.frame(
    Term     = rownames(coef_estimates),
    Estimate = coef_estimates[, "Estimate"] * 1e3,
    CI       = paste0(
                 conf_intervals[, 1], " – ",
                 conf_intervals[, 2]
               ),
    P_value  = coef_estimates[, "Pr(>|t|)"],
    P_adjust = p.adjust(coef_estimates[, "Pr(>|t|)"], "BH"),
    row.names = NULL
  )
  
  return(summary_table)
}

testMetadata(cp_tongue, 1, processedTongue_cp)
testMetadata(cp_saliva, 1, processedSaliva_cp)
testMetadata(cp_cytokines, 1, processedCytokines_cp)
testMetadata(cp_biochemistry, 1, processedBiochemistry_cp)

testMetadata(npls_tongue, 1, processedTongue_npls)
testMetadata(npls_saliva, 1, processedSaliva_npls)
testMetadata(npls_cyto, 1, processedCytokines_npls)
testMetadata(npls_bio, 1, processedBiochemistry_npls)

testMetadata(acmtf_model, 1, processedTongue_acmtf)

testMetadata(acmtfr_model, 1, processedTongue_acmtf)
```

## Comparison

```{r compare models using FMS}
plotlistFMS = list()
plotlistA = list()
plotlistB = list()
plotlistC = list()
iterator = 1
midpoint = 0.50
size = 4

# Tongue microbiome
CPmeta = processedTongue_cp
NPLSmeta = processedTongue_npls
ACMTFmeta = processedTongue_acmtf
cp_model = cp_tongue
npls_model = npls_tongue
acmtf_mode = 2

part1 = cbind(CPmeta$mode1, cp_model$Fac[[1]])
colnames(part1) = c("subject", "GenderID", paste0("CP (", 1:ncol(cp_model$Fac[[1]]), ")"))
part2 = cbind(NPLSmeta$mode1, npls_model$Fac[[1]])
colnames(part2) = c("subject", "GenderID", paste0("NPLS (", 1:ncol(npls_model$Fac[[1]]), ")"))
part3 = cbind(ACMTFmeta$mode1, acmtf_model$Fac[[1]], acmtfr_model$Fac[[1]])
colnames(part3) = c("subject", "GenderID", paste0("ACMTF (", 1:ncol(acmtf_model$Fac[[1]]), ")"), paste0("ACMTFR (", 1:ncol(acmtfr_model$Fac[[1]]), ")"))
A = part1 %>% inner_join(part2) %>% inner_join(part3) %>% select(-subject, -GenderID) %>% as.data.frame()

part1 = cbind(CPmeta$mode2, cp_model$Fac[[2]], npls_model$Fac[[2]])
colnames(part1) = c("zOTU", "Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species", paste0("CP (", 1:ncol(cp_model$Fac[[1]]), ")"), paste0("NPLS (", 1:ncol(npls_model$Fac[[1]]), ")"))
part2 = cbind(ACMTFmeta$mode2, acmtf_model$Fac[[acmtf_mode]], acmtfr_model$Fac[[acmtf_mode]])
colnames(part2) = c("zOTU", "Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species", paste0("ACMTF (", 1:ncol(acmtf_model$Fac[[1]]), ")"), paste0("ACMTF-R (", 1:ncol(acmtfr_model$Fac[[1]]), ")"))
B = part1 %>% inner_join(part2) %>% select(-zOTU, -Kingdom, -Phylum, -Class, -Order, -Family, -Genus, -Species) %>% as.data.frame()
C = cbind(cp_model$Fac[[3]], npls_model$Fac[[3]], acmtf_model$Fac[[acmtf_mode+1]], acmtfr_model$Fac[[acmtf_mode+1]])

TCC_A = matrix(NA, nrow=ncol(A), ncol=ncol(A))
TCC_B = matrix(NA, nrow=ncol(B), ncol=ncol(B))
TCC_C = matrix(NA, nrow=ncol(C), ncol=ncol(C))
for(i in 1:ncol(B)){
  for(j in 1:ncol(B)){
    TCC_A[i,j] = calculateTCC(A[,i], A[,j])
    TCC_B[i,j] = calculateTCC(B[,i], B[,j])
    TCC_C[i,j] = calculateTCC(C[,i], C[,j])
  }
}

labels = c(paste0("CP (", 1:ncol(cp_model$Fac[[1]]), ")"), paste0("NPLS (", 1:ncol(npls_model$Fac[[1]]), ")"), paste0("ACMTF (", 1:ncol(acmtf_model$Fac[[1]]), ")"), paste0("ACMTF-R (", 1:ncol(acmtfr_model$Fac[[1]]), ")"))

FMS = (TCC_A * TCC_B * TCC_C)
diag(FMS) = NA
FMS[lower.tri(FMS)] = NA
plotlistFMS[[iterator]] = FMS %>%
  as_tibble() %>%
  mutate(model = paste0("V", 1:ncol(A))) %>%
  pivot_longer(-model) %>%
  ggplot(aes(x=as.factor(model),y=as.factor(name),fill=value)) +
  geom_tile(col="black") +
  geom_text(aes(label = sprintf("%.2f", value)), size = size) +
  scale_x_discrete(name="", labels=labels) +
  scale_y_discrete(name="", labels=labels) +
  scale_fill_gradient(name="FMS", low="#FFFFFF", high="#1B7837", na.value="black", limits=c(0,1.01)) +
  theme(legend.position="na", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), text=element_text(size=16))

combinedTCC = matrix(NA, nrow=nrow(TCC_A), ncol=ncol(TCC_A))
combinedTCC[upper.tri(combinedTCC)] = TCC_A[upper.tri(TCC_A)]
combinedTCC[lower.tri(combinedTCC)] = TCC_B[lower.tri(TCC_B)]
plotlistA[[iterator]] = combinedTCC %>%
  as_tibble() %>%
  mutate(model = paste0("V", 1:ncol(A))) %>%
  pivot_longer(-model) %>%
  ggplot(aes(x=as.factor(model),y=as.factor(name),fill=value)) +
  geom_tile(col="black") +
  geom_text(aes(label = sprintf("%.2f", value)), size = size) +
  scale_x_discrete(name="", labels=labels) +
  scale_y_discrete(name="", labels=labels) +
  scale_fill_gradient(name="TCC", low="#FFFFFF", high="#1B7837", na.value="black", limits=c(0,1.01)) +
  theme(legend.position="na", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), text=element_text(size=16))

iterator = iterator + 1

# Salivary microbiome
CPmeta = processedSaliva_cp
NPLSmeta = processedSaliva_npls
ACMTFmeta = processedSaliva_acmtf
cp_model = cp_saliva
npls_model = npls_saliva
acmtf_mode = 4

part1 = cbind(CPmeta$mode1, cp_model$Fac[[1]])
colnames(part1) = c("subject", "GenderID", paste0("CP (", 1:ncol(cp_model$Fac[[1]]), ")"))
part2 = cbind(NPLSmeta$mode1, npls_model$Fac[[1]])
colnames(part2) = c("subject", "GenderID", paste0("NPLS (", 1:ncol(npls_model$Fac[[1]]), ")"))
part3 = cbind(ACMTFmeta$mode1, acmtf_model$Fac[[1]], acmtfr_model$Fac[[1]])
colnames(part3) = c("subject", "GenderID", paste0("ACMTF (", 1:ncol(acmtf_model$Fac[[1]]), ")"), paste0("ACMTFR (", 1:ncol(acmtfr_model$Fac[[1]]), ")"))
A = part1 %>% inner_join(part2) %>% inner_join(part3) %>% select(-subject, -GenderID) %>% as.data.frame()

part1 = cbind(CPmeta$mode2, cp_model$Fac[[2]], npls_model$Fac[[2]])
colnames(part1) = c("zOTU", "Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species", paste0("CP (", 1:ncol(cp_model$Fac[[1]]), ")"), paste0("NPLS (", 1:ncol(npls_model$Fac[[1]]), ")"))
part2 = cbind(ACMTFmeta$mode2, acmtf_model$Fac[[acmtf_mode]], acmtfr_model$Fac[[acmtf_mode]])
colnames(part2) = c("zOTU", "Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species", paste0("ACMTF (", 1:ncol(acmtf_model$Fac[[1]]), ")"), paste0("ACMTF-R (", 1:ncol(acmtfr_model$Fac[[1]]), ")"))
B = part1 %>% inner_join(part2) %>% select(-zOTU, -Kingdom, -Phylum, -Class, -Order, -Family, -Genus, -Species) %>% as.data.frame()
C = cbind(cp_model$Fac[[3]], npls_model$Fac[[3]], acmtf_model$Fac[[acmtf_mode+1]], acmtfr_model$Fac[[acmtf_mode+1]])

TCC_A = matrix(NA, nrow=ncol(A), ncol=ncol(A))
TCC_B = matrix(NA, nrow=ncol(B), ncol=ncol(B))
TCC_C = matrix(NA, nrow=ncol(C), ncol=ncol(C))
for(i in 1:ncol(B)){
  for(j in 1:ncol(B)){
    TCC_A[i,j] = calculateTCC(A[,i], A[,j])
    TCC_B[i,j] = calculateTCC(B[,i], B[,j])
    TCC_C[i,j] = calculateTCC(C[,i], C[,j])
  }
}

labels = c(paste0("CP (", 1:ncol(cp_model$Fac[[1]]), ")"), paste0("NPLS (", 1:ncol(npls_model$Fac[[1]]), ")"), paste0("ACMTF (", 1:ncol(acmtf_model$Fac[[1]]), ")"), paste0("ACMTF-R (", 1:ncol(acmtfr_model$Fac[[1]]), ")"))

FMS = (TCC_A * TCC_B * TCC_C)
diag(FMS) = NA
FMS[lower.tri(FMS)] = NA
plotlistFMS[[iterator]] = FMS %>%
  as_tibble() %>%
  mutate(model = paste0("V", 1:ncol(A))) %>%
  pivot_longer(-model) %>%
  ggplot(aes(x=as.factor(model),y=as.factor(name),fill=value)) +
  geom_tile(col="black") +
  geom_text(aes(label = sprintf("%.2f", value)), size = size) +
  scale_x_discrete(name="", labels=labels) +
  scale_y_discrete(name="", labels=labels) +
  scale_fill_gradient(name="FMS", low="#FFFFFF", high="#1B7837", na.value="black", limits=c(0,1.01)) +
  theme(legend.position="na", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), text=element_text(size=16))

combinedTCC = matrix(NA, nrow=nrow(TCC_A), ncol=ncol(TCC_A))
combinedTCC[upper.tri(combinedTCC)] = TCC_A[upper.tri(TCC_A)]
combinedTCC[lower.tri(combinedTCC)] = TCC_B[lower.tri(TCC_B)]
plotlistA[[iterator]] = combinedTCC %>%
  as_tibble() %>%
  mutate(model = paste0("V", 1:ncol(A))) %>%
  pivot_longer(-model) %>%
  ggplot(aes(x=as.factor(model),y=as.factor(name),fill=value)) +
  geom_tile(col="black") +
  geom_text(aes(label = sprintf("%.2f", value)), size = size) +
  scale_x_discrete(name="", labels=labels) +
  scale_y_discrete(name="", labels=labels) +
  scale_fill_gradient(name="TCC", low="#FFFFFF", high="#1B7837", na.value="black", limits=c(0,1.01)) +
  theme(legend.position="na", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), text=element_text(size=16))

iterator = iterator + 1

# Salivary cytokines
CPmeta = processedCytokines_cp
NPLSmeta = processedCytokines_npls
ACMTFmeta = processedCytokines_acmtf
cp_model = cp_cytokines
npls_model = npls_cyto
acmtf_mode = 6

part1 = cbind(CPmeta$mode1, cp_model$Fac[[1]])
colnames(part1) = c("subject", "GenderID", paste0("CP (", 1:ncol(cp_model$Fac[[1]]), ")"))
part2 = cbind(NPLSmeta$mode1, npls_model$Fac[[1]])
colnames(part2) = c("subject", "GenderID", paste0("NPLS (", 1:ncol(npls_model$Fac[[1]]), ")"))
part3 = cbind(ACMTFmeta$mode1, acmtf_model$Fac[[1]], acmtfr_model$Fac[[1]])
colnames(part3) = c("subject", "GenderID", paste0("ACMTF (", 1:ncol(acmtf_model$Fac[[1]]), ")"), paste0("ACMTFR (", 1:ncol(acmtfr_model$Fac[[1]]), ")"))
A = part1 %>% inner_join(part2) %>% inner_join(part3) %>% select(-subject, -GenderID) %>% as.data.frame()

part1 = cbind(CPmeta$mode2, cp_model$Fac[[2]], npls_model$Fac[[2]])
colnames(part1) = c("Cytokine", paste0("CP (", 1:ncol(cp_model$Fac[[1]]), ")"), paste0("NPLS (", 1:ncol(npls_model$Fac[[1]]), ")"))
part2 = cbind(ACMTFmeta$mode2, acmtf_model$Fac[[acmtf_mode]], acmtfr_model$Fac[[acmtf_mode]])
colnames(part2) = c("Cytokine", paste0("ACMTF (", 1:ncol(acmtf_model$Fac[[1]]), ")"), paste0("ACMTF-R (", 1:ncol(acmtfr_model$Fac[[1]]), ")"))
B = part1 %>% inner_join(part2) %>% select(-Cytokine) %>% as.data.frame()
C = cbind(cp_model$Fac[[3]], npls_model$Fac[[3]], acmtf_model$Fac[[acmtf_mode+1]], acmtfr_model$Fac[[acmtf_mode+1]])

TCC_A = matrix(NA, nrow=ncol(A), ncol=ncol(A))
TCC_B = matrix(NA, nrow=ncol(B), ncol=ncol(B))
TCC_C = matrix(NA, nrow=ncol(C), ncol=ncol(C))
for(i in 1:ncol(B)){
  for(j in 1:ncol(B)){
    TCC_A[i,j] = calculateTCC(A[,i], A[,j])
    TCC_B[i,j] = calculateTCC(B[,i], B[,j])
    TCC_C[i,j] = calculateTCC(C[,i], C[,j])
  }
}

labels = c(paste0("CP (", 1:ncol(cp_model$Fac[[1]]), ")"), paste0("NPLS (", 1:ncol(npls_model$Fac[[1]]), ")"), paste0("ACMTF (", 1:ncol(acmtf_model$Fac[[1]]), ")"), paste0("ACMTF-R (", 1:ncol(acmtfr_model$Fac[[1]]), ")"))

FMS = (TCC_A * TCC_B * TCC_C)
diag(FMS) = NA
FMS[lower.tri(FMS)] = NA
plotlistFMS[[iterator]] = FMS %>%
  as_tibble() %>%
  mutate(model = paste0("V", 1:ncol(A))) %>%
  pivot_longer(-model) %>%
  ggplot(aes(x=as.factor(model),y=as.factor(name),fill=value)) +
  geom_tile(col="black") +
  geom_text(aes(label = sprintf("%.2f", value)), size = size) +
  scale_x_discrete(name="", labels=labels) +
  scale_y_discrete(name="", labels=labels) +
  scale_fill_gradient(name="FMS", low="#FFFFFF", high="#1B7837", na.value="black", limits=c(0,1.01)) +
  theme(legend.position="na", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), text=element_text(size=16))

combinedTCC = matrix(NA, nrow=nrow(TCC_A), ncol=ncol(TCC_A))
combinedTCC[upper.tri(combinedTCC)] = TCC_A[upper.tri(TCC_A)]
combinedTCC[lower.tri(combinedTCC)] = TCC_B[lower.tri(TCC_B)]
plotlistA[[iterator]] = combinedTCC %>%
  as_tibble() %>%
  mutate(model = paste0("V", 1:ncol(A))) %>%
  pivot_longer(-model) %>%
  ggplot(aes(x=as.factor(model),y=as.factor(name),fill=value)) +
  geom_tile(col="black") +
  geom_text(aes(label = sprintf("%.2f", value)), size = size) +
  scale_x_discrete(name="", labels=labels) +
  scale_y_discrete(name="", labels=labels) +
  scale_fill_gradient(name="TCC", low="#FFFFFF", high="#1B7837", na.value="black", limits=c(0,1.01)) +
  theme(legend.position="na", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), text=element_text(size=16))

iterator = iterator + 1

# Salivary biochemistry
CPmeta = processedBiochemistry_cp
NPLSmeta = processedBiochemistry_npls
ACMTFmeta = processedBiochemistry_acmtf
cp_model = cp_biochemistry
npls_model = npls_bio
acmtf_mode = 8

part1 = cbind(CPmeta$mode1, cp_model$Fac[[1]])
colnames(part1) = c("subject", "GenderID", paste0("CP (", 1:ncol(cp_model$Fac[[1]]), ")"))
part2 = cbind(NPLSmeta$mode1, npls_model$Fac[[1]])
colnames(part2) = c("subject", "GenderID", paste0("NPLS (", 1:ncol(npls_model$Fac[[1]]), ")"))
part3 = cbind(ACMTFmeta$mode1, acmtf_model$Fac[[1]], acmtfr_model$Fac[[1]])
colnames(part3) = c("subject", "GenderID", paste0("ACMTF (", 1:ncol(acmtf_model$Fac[[1]]), ")"), paste0("ACMTFR (", 1:ncol(acmtfr_model$Fac[[1]]), ")"))
A = part1 %>% inner_join(part2) %>% inner_join(part3) %>% select(-subject, -GenderID) %>% as.data.frame()

part1 = cbind(CPmeta$mode2, cp_model$Fac[[2]], npls_model$Fac[[2]])
colnames(part1) = c("Biochemistry", paste0("CP (", 1:ncol(cp_model$Fac[[1]]), ")"), paste0("NPLS (", 1:ncol(npls_model$Fac[[1]]), ")"))
part2 = cbind(ACMTFmeta$mode2, acmtf_model$Fac[[acmtf_mode]], acmtfr_model$Fac[[acmtf_mode]])
colnames(part2) = c("Biochemistry", paste0("ACMTF (", 1:ncol(acmtf_model$Fac[[1]]), ")"), paste0("ACMTF-R (", 1:ncol(acmtfr_model$Fac[[1]]), ")"))
B = part1 %>% inner_join(part2) %>% select(-Biochemistry) %>% as.data.frame()
C = cbind(cp_model$Fac[[3]], npls_model$Fac[[3]], acmtf_model$Fac[[acmtf_mode+1]], acmtfr_model$Fac[[acmtf_mode+1]])

TCC_A = matrix(NA, nrow=ncol(A), ncol=ncol(A))
TCC_B = matrix(NA, nrow=ncol(B), ncol=ncol(B))
TCC_C = matrix(NA, nrow=ncol(C), ncol=ncol(C))
for(i in 1:ncol(B)){
  for(j in 1:ncol(B)){
    TCC_A[i,j] = calculateTCC(A[,i], A[,j])
    TCC_B[i,j] = calculateTCC(B[,i], B[,j])
    TCC_C[i,j] = calculateTCC(C[,i], C[,j])
  }
}

labels = c(paste0("CP (", 1:ncol(cp_model$Fac[[1]]), ")"), paste0("NPLS (", 1:ncol(npls_model$Fac[[1]]), ")"), paste0("ACMTF (", 1:ncol(acmtf_model$Fac[[1]]), ")"), paste0("ACMTF-R (", 1:ncol(acmtfr_model$Fac[[1]]), ")"))

FMS = (TCC_A * TCC_B * TCC_C)
diag(FMS) = NA
FMS[lower.tri(FMS)] = NA
plotlistFMS[[iterator]] = FMS %>%
  as_tibble() %>%
  mutate(model = paste0("V", 1:ncol(A))) %>%
  pivot_longer(-model) %>%
  ggplot(aes(x=as.factor(model),y=as.factor(name),fill=value)) +
  geom_tile(col="black") +
  geom_text(aes(label = sprintf("%.2f", value)), size = size) +
  scale_x_discrete(name="", labels=labels) +
  scale_y_discrete(name="", labels=labels) +
  scale_fill_gradient(name="FMS", low="#FFFFFF", high="#1B7837", na.value="black", limits=c(0,1.01)) +
  theme(legend.position="na", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), text=element_text(size=16))

combinedTCC = matrix(NA, nrow=nrow(TCC_A), ncol=ncol(TCC_A))
combinedTCC[upper.tri(combinedTCC)] = TCC_A[upper.tri(TCC_A)]
combinedTCC[lower.tri(combinedTCC)] = TCC_B[lower.tri(TCC_B)]
plotlistA[[iterator]] = combinedTCC %>%
  as_tibble() %>%
  mutate(model = paste0("V", 1:ncol(A))) %>%
  pivot_longer(-model) %>%
  ggplot(aes(x=as.factor(model),y=as.factor(name),fill=value)) +
  geom_tile(col="black") +
  geom_text(aes(label = sprintf("%.2f", value)), size = size) +
  scale_x_discrete(name="", labels=labels) +
  scale_y_discrete(name="", labels=labels) +
  scale_fill_gradient(name="TCC", low="#FFFFFF", high="#1B7837", na.value="black", limits=c(0,1.01)) +
  theme(legend.position="na", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), text=element_text(size=16))

iterator = iterator + 1

ggarrange(plotlistFMS[[1]], plotlistA[[1]], nrow=1, ncol=2)
ggarrange(plotlistFMS[[2]], plotlistA[[2]], nrow=1, ncol=2)
ggarrange(plotlistFMS[[3]], plotlistA[[3]], nrow=1, ncol=2)
ggarrange(plotlistFMS[[4]], plotlistA[[4]], nrow=1, ncol=2)
```


